/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnngl_misc_ScreenCapture */

#ifndef _Included_com_jnngl_misc_ScreenCapture
#define _Included_com_jnngl_misc_ScreenCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnngl_misc_ScreenCapture
 * Method:    win32applications
 * Signature: ()[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jnngl_misc_ScreenCapture_win32applications
  (JNIEnv *, jobject);

/*
 * Class:     com_jnngl_misc_ScreenCapture
 * Method:    win32screenScreenshot
 * Signature: ([I[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_jnngl_misc_ScreenCapture_win32screenScreenshot
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     com_jnngl_misc_ScreenCapture
 * Method:    win32appScreenshot
 * Signature: (Ljava/nio/ByteBuffer;[I[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_jnngl_misc_ScreenCapture_win32appScreenshot
  (JNIEnv *, jobject, jobject, jintArray, jintArray);

/*
 * Class:     com_jnngl_misc_ScreenCapture
 * Method:    win32appName
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnngl_misc_ScreenCapture_win32appName
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
