/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnngl_system_NativeWindowApplication */

#ifndef _Included_com_jnngl_system_NativeWindowApplication
#define _Included_com_jnngl_system_NativeWindowApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnngl_system_NativeWindowApplication
 * Method:    _Init
 * Signature: (JLjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_NativeWindowApplication__1Init
  (JNIEnv *, jobject, jlong, jstring, jobjectArray);

/*
 * Class:     com_jnngl_system_NativeWindowApplication
 * Method:    _OnClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnngl_system_NativeWindowApplication__1OnClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jnngl_system_NativeWindowApplication
 * Method:    _Update
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_NativeWindowApplication__1Update
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jnngl_system_NativeWindowApplication
 * Method:    _Render
 * Signature: (JLjava/awt/Graphics2D;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_NativeWindowApplication__1Render
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jnngl_system_NativeWindowApplication
 * Method:    _ProcessInput
 * Signature: (JIIZ)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_NativeWindowApplication__1ProcessInput
  (JNIEnv *, jobject, jlong, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
