/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnngl_system_WebBrowserBootstrapV2 */

#ifndef _Included_com_jnngl_system_WebBrowserBootstrapV2
#define _Included_com_jnngl_system_WebBrowserBootstrapV2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnngl_system_WebBrowserBootstrapV2
 * Method:    InitCEF
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnngl_system_WebBrowserBootstrapV2_InitCEF
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jnngl_system_WebBrowserBootstrapV2
 * Method:    CreateBrowser
 * Signature: (II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_jnngl_system_WebBrowserBootstrapV2_CreateBrowser
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jnngl_system_WebBrowserBootstrapV2
 * Method:    Update
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_WebBrowserBootstrapV2_Update
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_jnngl_system_WebBrowserBootstrapV2
 * Method:    GetPixels
 * Signature: (Ljava/nio/ByteBuffer;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jnngl_system_WebBrowserBootstrapV2_GetPixels
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jnngl_system_WebBrowserBootstrapV2
 * Method:    ProcessTouch
 * Signature: (Ljava/nio/ByteBuffer;IIZ)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_WebBrowserBootstrapV2_ProcessTouch
  (JNIEnv *, jclass, jobject, jint, jint, jboolean);

/*
 * Class:     com_jnngl_system_WebBrowserBootstrapV2
 * Method:    RunLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_WebBrowserBootstrapV2_RunLoop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
