/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnngl_system_BrowserImpl_Native */

#ifndef _Included_com_jnngl_system_BrowserImpl_Native
#define _Included_com_jnngl_system_BrowserImpl_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_getURL
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1getURL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_getTitle
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1getTitle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_createCef
 * Signature: (IILjava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1createCef
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_close
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1close
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_render
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1render
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_getSize
 * Signature: (Ljava/nio/ByteBuffer;[I[I)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1getSize
  (JNIEnv *, jobject, jobject, jintArray, jintArray);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_getPixels
 * Signature: (Ljava/nio/ByteBuffer;[I)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1getPixels
  (JNIEnv *, jobject, jobject, jintArray);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_keyTyped
 * Signature: (Ljava/nio/ByteBuffer;CLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1keyTyped
  (JNIEnv *, jobject, jobject, jchar, jstring);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_setSize
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1setSize
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_goBack
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1goBack
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_goForward
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1goForward
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_loadURL
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1loadURL
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_canGoBack
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1canGoBack
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_canGoForward
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1canGoForward
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jnngl_system_BrowserImpl_Native
 * Method:    N_click
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_com_jnngl_system_BrowserImpl_1Native_N_1click
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
